# -*- coding: utf-8 -*-
"""pandas/datos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eCiWfBgLfNQJVzXIGq4e85go9M5Q8dkh

#**Libreria de pandas 🐼**
"""

import pandas as pd

ruta = "https://raw.githubusercontent.com/VMjavier/claseAnalisisDatos/refs/heads/main/veterinaria_colombia.csv "
df = pd.read_csv(ruta)
df.head()

df.info() #object debe tener datos alphabeticos o alphanumericos
# y los datos numericos deben ser float(no enteros) o int(enteros)

df.columns

df.isnull().sum()

df.shape #filas y columnas

"""#**LIMPIEZA**🧹

"""

df.columns

df.columns = df.columns.str.strip().str.lower().str.replace(' ','_')

df.columns

df.rename(columns = {"nombre": "nombre_mascota"}, inplace= "true")

df.columns

"""#**Eliminar filas o columnas completamente vacias**🚮"""

df.dropna(axis = 0, how = "all", inplace = True ) #fila = 0
df.dropna(axis = 1, how = "all", inplace = True ) #columna = 1

df.shape

df.drop(columns = ["nombre_mascota"], inplace = True)

df.columns